CAMERA_INDEX = "C:/Users/Doğukan/Desktop/Proje/Teknofest/Dataset/video_1_1920x1080.mp4"

WINDOW_MAIN = "Main Frame"
WINDOW_LEFT_EYE = "Left Eye ROI"
WINDOW_RIGHT_EYE = "Right Eye ROI"
WINDOW_MOUTH = "Mouth ROI"

EYE_PADDING_X = 8
EYE_PADDING_Y = 8

MOUTH_PADDING_X = 12
MOUTH_PADDING_Y = 12

EMA_ALPHA_EAR = 0.4
EMA_ALPHA_MAR = 0.35


EAR_CLOSE_THRESHOLD = 0.22
EAR_OPEN_THRESHOLD = 0.23
MIN_CLOSED_FRAMES_FOR_BLINK = 2
BLINK_COOLDOWN_FRAMES = 6